public enum LandlordActionId {
    WORK_THE_ROOM,
    RUN_A_SPECIAL,
    PUSHY_UPSELL,
    LOCALS_NIGHT,
    PARTNER_PROMO,
    FLIRT_FOR_BUZZ,
    VIP_HOSPITALITY,
    INVITE_REVIEWER,
    PLANT_A_RUMOR,
    SPONSOR_CHARITY,
    EXCLUSIVE_DOOR_POLICY,
    QUIET_FIXER,
    HIGH_SOCIETY_NETWORKING,
    CONTROL_THE_NARRATIVE,
    SABOTAGE_RIVAL
}
